### ISSUE TITLE
ImportError after installing on MacOS Ventura

### ISSUE THREAD

**Issue by divan** [TheR1D/shell_gpt#18]
Installed it by instructions (`pip install shell-gpt --user`) and getting this^

```sgpt
Traceback (most recent call last):
  File "/Users/divan/Library/Python/3.9/bin/sgpt", line 5, in <module>
    from sgpt import entry_point
  File "/Users/divan/Library/Python/3.9/lib/python/site-packages/sgpt.py", line 9, in <module>
    from utils import loading_spinner
ImportError: cannot import name 'loading_spinner' from 'utils' (/Users/divan/Library/Python/3.9/lib/python/site-packages/utils/__init__.py)
```

**Comment by TheR1D** [comment]
Try it with pip3 `pip3 install shell-gpt --user --upgrade` if it doesn't help, share output of following commands:
```
pip3 show shell-gpt
echo $PATH
```

**Comment by divan** [comment]
@TheR1D thanks for the quick response. I tried with `--upgrade` - nothing changed.

Here is an output of these two commands:

```
pip3 show shell-gpt
echo $PATH
Name: shell-gpt
Version: 0.4
Summary: CLI App allows to query OpenAI Chat GPT models using API.
Home-page: https://github.com/ther1d/shell_gpt
Author: Farkhod Sadykov
Author-email: farkhod.sadykov@gmail.com
License:
Location: /Users/divan/Library/Python/3.9/lib/python/site-packages
Requires: requests, rich, typer
Required-by:
/opt/homebrew/opt/ruby/bin:/Users/divan/Library/Application Support/edgedb/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Frameworks/EdgeDB.framework/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/divan/.cargo/bin:/Users/divan/bin:/Users/divan/go/bin:/opt/homebrew/bin:/usr/local/go/bin:/Users/divan/flutter/bin:/usr/local/mysql/bin:/Users/divan/bin/monarch/bin:/opt/homebrew/Cellar/node/17.7.2/bin/:/Users/divan/.pub-cache/bin:/Users/divan/Library/Python/3.8/bin:/Users/divan/Library/Python/3.9/bin
```

**Comment by TheR1D** [comment]
@divan @andersmmg A new patch has been published on PyPI just now. Please run the following command: `pip3 install shell-gpt --user --upgrade`. Make sure you have the latest version (0.4.1) installed `pip3 show shell-gpt`. This should fix the issue you have.

**Comment by andersmmg** [comment]
Looks like that fixed it for me!

**Comment by divan** [comment]
@TheR1D awesome, thanks! Works.
