### ISSUE TITLE
Sample config file in the README.md wrong?

### ISSUE THREAD

**Issue by fy2** [TheR1D/shell_gpt#209]
sgpt fails upon fresh installation (no errors during installation)

$ sgpt "what are the colors of a rainbow"

```bash
Traceback (most recent call last):
  File "/Users/f.yalcin/.pyenv/versions/3.11.2/bin/sgpt", line 5, in <module>
    from sgpt import cli
  File "/Users/f.yalcin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sgpt/__init__.py", line 1, in <module>
    from .app import main as main
  File "/Users/f.yalcin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sgpt/app.py", line 15, in <module>
    from sgpt.client import OpenAIClient
  File "/Users/f.yalcin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sgpt/client.py", line 8, in <module>
    from .config import cfg
  File "/Users/f.yalcin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sgpt/config.py", line 82, in <module>
    cfg = Config(SHELL_GPT_CONFIG_PATH, **DEFAULT_CONFIG)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/f.yalcin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sgpt/config.py", line 40, in __init__
    self._read()
  File "/Users/f.yalcin/.pyenv/versions/3.11.2/lib/python3.11/site-packages/sgpt/config.py", line 71, in _read
    key, value = line.strip().split("=")
    ^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

My Python version (installed through `pyenv):
$ python --version
Python 3.11.2

Config (` ~/.config/shell_gpt/.sgptrc`)
```text
# API key, also it is possible to define OPENAI_API_KEY env.
OPENAI_API_KEY=**************************************************
# OpenAI host, useful if you would like to use proxy.
OPENAI_API_HOST=https://api.openai.com
# Max amount of cached message per chat session.
CHAT_CACHE_LENGTH=100
# Chat cache folder.
CHAT_CACHE_PATH=/tmp/shell_gpt/chat_cache
# Request cache length (amount).
CACHE_LENGTH=100
# Request cache folder.
CACHE_PATH=/tmp/shell_gpt/cache
# Request timeout in seconds.
REQUEST_TIMEOUT=60
# Default OpenAI model to use.
DEFAULT_MODEL=gpt-3.5-turbo
# Default color for OpenAI completions.
DEFAULT_COLOR=magenta
# Force use system role messages (not recommended).
SYSTEM_ROLES=false
```

**Comment by fy2** [comment]
Looks like if I remove the config file and enter the OpenAI key into the prompt, it works. So, is the default config wrong? (the one on your README.md):

```bash
$ sgpt "what are the colors of a rainbow"
Please enter your OpenAI API key:


The colors of a rainbow are red, orange, yellow, green, blue, indigo, and violet.
```

**Comment by fy2** [comment]
I may have entered a typo, I will close it for now!
