### ISSUE TITLE
Erro on Ubuntu 22.04

### ISSUE THREAD

**Issue by xereda** [TheR1D/shell_gpt#238]
An error occurs when running sgpt:

```
 ~> sgpt what is my ip                                                                                                                                               ter 09 mai 2023 12:21:40
Traceback (most recent call last):
  File "/home/xereda/.local/bin/sgpt", line 5, in <module>
    from sgpt import cli
  File "/home/xereda/.local/lib/python3.10/site-packages/sgpt/__init__.py", line 1, in <module>
    from .app import main as main
  File "/home/xereda/.local/lib/python3.10/site-packages/sgpt/app.py", line 15, in <module>
    from sgpt.client import OpenAIClient
  File "/home/xereda/.local/lib/python3.10/site-packages/sgpt/client.py", line 8, in <module>
    from .config import cfg
  File "/home/xereda/.local/lib/python3.10/site-packages/sgpt/config.py", line 82, in <module>
    cfg = Config(SHELL_GPT_CONFIG_PATH, **DEFAULT_CONFIG)
  File "/home/xereda/.local/lib/python3.10/site-packages/sgpt/config.py", line 40, in __init__
    self._read()
  File "/home/xereda/.local/lib/python3.10/site-packages/sgpt/config.py", line 71, in _read
    key, value = line.strip().split("=")
ValueError: not enough values to unpack (expected 2, got 1)
```

OS details:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

**Comment by wowitsjack** [comment]
Missing quote marks around the input question.

**Comment by c8libur** [comment]
You can remove .config/shell_gpt fitstly.Then execute command "python3 -m sgpt".
