### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by greedkiss** [TheR1D/shell_gpt#309]
I got an error when I was running the test  

`sgpt "nginx default config file location"`

The error  I got
```
Traceback (most recent call last):
  File "/home/flipped/.local/bin/sgpt", line 5, in <module>
    from sgpt import cli
  File "/home/flipped/.local/lib/python3.8/site-packages/sgpt/__init__.py", line 1, in <module>
    from .app import main as main
  File "/home/flipped/.local/lib/python3.8/site-packages/sgpt/app.py", line 9, in <module>
    from sgpt.config import cfg
  File "/home/flipped/.local/lib/python3.8/site-packages/sgpt/config.py", line 83, in <module>
    cfg = Config(SHELL_GPT_CONFIG_PATH, **DEFAULT_CONFIG)
  File "/home/flipped/.local/lib/python3.8/site-packages/sgpt/config.py", line 40, in __init__
    self._read()
  File "/home/flipped/.local/lib/python3.8/site-packages/sgpt/config.py", line 72, in _read
    key, value = line.strip().split("=")
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by greedkiss** [comment]
I created the .sgptrc configuration file manually myself, probably in the wrong format
