### ISSUE TITLE
Is Home directory of /home/* hard-coded?

### ISSUE THREAD

**Issue by TechDufus** [TheR1D/shell_gpt#350]
After moving the home directory for my user profile from `/home/user` to `/app/home/user`, and even reinstalling this pip package, when running the `~/.local/bin/sgpt` bin I'm getting the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.config/shell_gpt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/home/user/.local/bin/sgpt", line 5, in <module>
    from sgpt import cli
  File "/app/home/user/.local/lib/python3.10/site-packages/sgpt/__init__.py", line 1, in <module>
    from .app import main as main
  File "/app/home/user/.local/lib/python3.10/site-packages/sgpt/app.py", line 17, in <module>
    from sgpt.handlers.chat_handler import ChatHandler
  File "/app/home/user/.local/lib/python3.10/site-packages/sgpt/handlers/chat_handler.py", line 10, in <module>
    from ..role import SystemRole
  File "/app/home/user/.local/lib/python3.10/site-packages/sgpt/role.py", line 197, in <module>
    SystemRole.create_defaults()
  File "/app/home/user/.local/lib/python3.10/site-packages/sgpt/role.py", line 65, in create_defaults
    cls.storage.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/user'
```

**Comment by gitmpr** [comment]
Try removing or changing the hardcoded PATH variables in the file `~/.config/shell_gpt/.sgpt`

**Comment by TechDufus** [comment]
> ~/.config/shell_gpt/.sgpt

I didn't know about this file `~/.config/shell_gpt/.sgptrc`

The var needing updating was `ROLE_STORAGE_PATH`

THANK YOU!
