### ISSUE TITLE
Potential Bug: Invalid Model ID Error When Using Ollama Models

### ISSUE THREAD

**Issue by hcal** [TheR1D/shell_gpt#599]
Description:
I encountered an issue when trying to use Ollama models with the shell_gpt tool. Despite following the instructions from the Ollama setup guide and ensuring that Ollama is running, I received an invalid model ID error. This happened on both Debian (I   modified the guide to account for using pipx on this install) and Fedora 40 (with a standard pip install exactly as described in the instructions).

Steps to Reproduce:

- Follow the [Ollama setup instructions](https://github.com/TheR1D/shell_gpt/wiki/Ollama) to set up shell_gpt.
- Ensure Ollama is running.
- Run the following command:
- sgpt --no-functions --model ollama/mistral:7b-instruct "Who are you?"
- Observe the error.

Error Output:

```
[opt] 🌗 ollama list
NAME ID SIZE MODIFIED
llama3.1 a23da2a80395 4.7 GB 21 minutes ago
mistral:7b-instruct f974a74358d6 4.1 GB 23 minutes ago

[opt] 🌘 sgpt --no-functions --model ollama/mistral:7b-instruct "Who are you?"

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/user1/.local/lib/python3.12/site-packages/sgpt/app.py:229 in main │
│ │
│ 226 │ │ │ functions=function_schemas, │
│ 227 │ │ ) │
│ 228 │ else: │
│ ❱ 229 │ │ full_completion = DefaultHandler(role_class, md).handle( │
│ 230 │ │ │ prompt=prompt, │
│ 231 │ │ │ model=model, │
│ 232 │ │ │ temperature=temperature, │
│ │
│ /home/user1/.local/lib/python3.12/site-packages/sgpt/handlers/handler.py:158 in handle │
│ │
│ 155 │ │ │ caching=caching, │
│ 156 │ │ │ **kwargs, │
│ 157 │ │ ) │
│ ❱ 158 │ │ return self.printer(generator, not disable_stream) │
│ │
│ /home/user1/.local/lib/python3.12/site-packages/sgpt/printer.py:23 in call │
│ │
│ 20 │ │
│ 21 │ def call(self, chunks: Generator[str, None, None], live: bool = True) -> str: │
│ 22 │ │ if live: │
│ ❱ 23 │ │ │ return self.live_print(chunks) │
│ │
│ /home/user1/.local/lib/python3.12/site-packages/sgpt/printer.py:38 in live_print │
│ │
│ 35 │ def live_print(self, chunks: Generator[str, None, None]) -> str: │
│ 36 │ │ full_completion = "" │
│ 37 │ │ with Live(console=self.console) as live: │
│ ❱ 38 │ │ │ for chunk in chunks: │
│ │
│ /home/user1/.local/lib/python3.12/site-packages/sgpt/cache.py:37 in wrapper │
│ │
│ 34 │ │ │ │ yield file.read_text() │
│ 35 │ │ │ │ return │
│ 36 │ │ │ result = "" │
│ ❱ 37 │ │ │ for i in func(*args, **kwargs): │
│ │
│ /home/user1/.local/lib/python3.12/site-packages/sgpt/handlers/handler.py:99 in get_completion │
│ │
│ 96 │ │ if is_shell_role or is_code_role or is dsc_shell_role: │
│ 97 │ │ │ functions = None │
│ 98 │ │ │
│ ❱ 99 │ │ response = completion( │
│ │
│ /home/user1/.local/lib/python3.12/site-packages/openai/_utils/_utils.py:277 in wrapper │
│ │
│ 274 │ │ │ │ │ else: │
│ 275 │ │ │ │ │ │ msg = f"Missing required argument: {quote(missing[0])}" │
│ 276 │ │ │ │ raise TypeError(msg) │
│ ❱ 277 │ │ │ return func(*args, **kwargs) │
│ │
│ /home/user1/.local/lib/python3.12/site-packages/openai/resources/chat/completions.py:646 in create │
│ │
│ 643 │ │ extra_body: Body | None = None, │
│ 644 │ │ timeout: float | httpx.Timeout | None | NotGiven = NOT_GIVEN, │
│ 645 │ ) -> ChatCompletion | Stream[ChatCompletionChunk]: │
│ ❱ 646 │ │ return self._post( │
│ │
│ /home/user1/.local/lib/python3.12/site-packages/openai/_base_client.py:1266 in post │
│ │
│ 1263 │ │ opts = FinalRequestOptions.construct( │
│ 1264 │ │ │ method="post", url=path, json_data=body, files=to_httpx_files(files), **opti │
│ 1265 │ │ ) │
│ ❱ 1266 │ │ return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=str │
│ │
│ /home/user1/.local/lib/python3.12/site-packages/openai/_base_client.py:942 in request │
│ │
│ 939 │ │ stream: bool = False, │
│ 940 │ │ stream_cls: type[_StreamT] | None = None, │
│ 941 │ ) -> ResponseT | _StreamT: │
│ ❱ 942 │ │ return self._request( │
│ │
│ /home/user1/.local/lib/python3.12/site-packages/openai/_base_client.py:1046 in _request │
│ │
│ 1043 │ │ │ │ err.response.read() │
│ 1044 │ │ │ │
│ 1045 │ │ │ log.debug("Re-raising status error") │
│ ❱ 1046 │ │ │ raise self._make_status_error_from_response(err.response) from None │
│ │
│ BadRequestError: Error code: 400 - {'error': {'message': 'invalid model ID', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

**Notes**:
- This is very likely user error, but it seems like a bug.
- I tested multiple models to ensure it wasn't an issue with a specific model.
- Any guidance or clarification on proper model ID usage or potential fixes would be greatly appreciated.

**Environment**:
- Debian (with pipx install)
- Fedora 40 (with standard pip install)

**Comment by kirkog86** [comment]
I can confirm shell_gpt can't operate with llama3.1:

![image](https://github.com/user-attachments/assets/b67d5315-1423-471a-8317-53d891951baa)

**Comment by zanagraf** [comment]
I've almost the same problem with mistral:latest

```
sgpt --model ollama/mistral:latest
Traceback (most recent call last):
  File "/home/agraf/.local/bin/sgpt", line 5, in <module>
    from sgpt import cli
  File "/home/agraf/.local/share/pipx/venvs/shell-gpt/lib/python3.12/site-packages/sgpt/__init__.py", line 1, in <module>
    from .app import main as main
  File "/home/agraf/.local/share/pipx/venvs/shell-gpt/lib/python3.12/site-packages/sgpt/app.py", line 13, in <module>
    from sgpt.handlers.chat_handler import ChatHandler
  File "/home/agraf/.local/share/pipx/venvs/shell-gpt/lib/python3.12/site-packages/sgpt/handlers/chat_handler.py", line 13, in <module>
    from .handler import Handler
  File "/home/agraf/.local/share/pipx/venvs/shell-gpt/lib/python3.12/site-packages/sgpt/handlers/handler.py", line 16, in <module>
    "api_key": cfg.get("OPENAI_API_KEY"),
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/agraf/.local/share/pipx/venvs/shell-gpt/lib/python3.12/site-packages/sgpt/config.py", line 85, in get
    raise UsageError(f"Missing config key: {key}")
click.exceptions.UsageError: Missing config key: OPENAI_API_KEY
```

**Comment by richburdon** [comment]
same here

**Comment by hakonw** [comment]
I had the same problem but fixed it by changing some variables in `~/.config/shell_gpt/.sgptrc`

after https://github.com/TheR1D/shell_gpt/wiki/Ollama
I changed `DEFAULT_MODEL` to `ollama/llama3.1`
`OPENAI_USE_FUNCTIONS` to `false`

and most importantly (and not documented in that wiki) `USE_LITELLM` to `true`

**Comment by zanagraf** [comment]
Thanks i will try it asap

**Comment by n0x00x** [comment]
On macbook pro max m1 i installed it with `pip install shell-gpt` here is my working config:
`
DEFAULT_MODEL=llama3.1:8b-instruct-q8_0
OPENAI_USE_FUNCTIONS=false
API_BASE_URL=http://127.0.0.1:11434/v1
USE_LITELLM=false
OPENAI_API_KEY=ollama
`

**Comment by zanagraf** [comment]
Will try it asap

**Comment by kirkog86** [comment]
Confirming Meta's llama-3.1 works

**Comment by zanagraf** [comment]
I forget to say it's working fine on me !

**Comment by hcal** [comment]
I have a solution that works for me so I'll close the issue.  Thanks all.
