### ISSUE TITLE
Running from source

### ISSUE THREAD

**Issue by levid0s** [TheR1D/shell_gpt#82]
How do we run this from source?

Looks like the app can't find its package references:

```
(venv) me@cwgpt-s0kd:~/shell_gpt/sgpt$ python app.py
Traceback (most recent call last):
  File "/home/me/shell_gpt/sgpt/app.py", line 20, in <module>
    from sgpt import config, make_prompt, OpenAIClient
ModuleNotFoundError: No module named 'sgpt'

(venv) me@cwgpt-s0kd:~/shell_gpt/tests$ python unittests.py
Traceback (most recent call last):
  File "/home/me/shell_gpt/tests/unittests.py", line 3, in <module>
    import requests_mock
ModuleNotFoundError: No module named 'requests_mock'
```

**Comment by levid0s** [comment]
Got it working like this.

```
me@cwgpt-s0kd:~/shell_gpt$ python3 -m sgpt "Hello, agent!"
Hello! How can I assist you today?
```
